directories:
  output: dist_electron
  buildResources: build
  app: dist_electron/bundled
files:
  - filter:
      - '**'
extends: null
appId: test.com
win:
  icon: public/lhquery.ico
electronVersion: 5.0.13
